### PR TITLE
Add LICENSE file explicitely

### PR DESCRIPTION
**Pull request by andresailer**
Just adding the file explicitly, so that github recognises it as well.
Followup for #127

### CODE REVIEW

**Comment by jmcarcell** [comment]
What does it change to do it in different PRs?

**Comment by andresailer** [comment]
The other one is already merged?

I want the license to show up in the repository overview
image

**Comment by andresailer** [comment]
Success:
image

**Comment by jmcarcell** [comment]
I thought the actual license file was in the first PR

**Pull request merged**
