### PR TITLE
Setting RPATH

### PR DESCRIPTION
**Pull request by kjvbrt**
BEGINRELEASENOTES
- Sets RPATH, so installed libs are not stripped
ENDRELEASENOTES

### CODE REVIEW

**Comment by andresailer** [comment]
Please use the whole RPATH things as linked to from  https://github.com/key4hep/k4-project-template/issues/12

**Comment by kjvbrt** [comment]
Would `K4FWCORE_SET_RPATH` option be useful?

**Comment by andresailer** [comment]
Thanks. Probably the option will be useful?

**Comment by kjvbrt** [comment]
I mean, whether there is a need to not set RPATH for the installed executables/libs.

**Comment by andresailer** [comment]
If you put everything in a "view" structure in the end, you don't want RPATH, so it could be useful.

**Comment by jmcarcell** [comment]
Let's merge this which would fix one issue. We should also have this in `k4-project-template`.

**Pull request merged**
