### PR TITLE
Add an argument for add_test_with_env not to have to repeat the test names

### PR DESCRIPTION
**Pull request by jmcarcell**
BEGINRELEASENOTES
- Add an argument for add_test_with_env not to have to repeat the test names
- Also add some documentation for the function since it's getting complicated

ENDRELEASENOTES

No more endless horizontal scrolling

### CODE REVIEW

**Comment by m-fila** [comment]
Would it make sense to move `CheckOutputFiles.py` from `options/ as it's not a steering file? To  `scripts/` for instance?

**Comment by jmcarcell** [comment]
Makes sense but we install the whole scripts folder, which I don't think it's a bad idea, and then this file would also be installed. I think it's fine as it is since it's only a folder for tests.

**Comment by m-fila** [comment]
Sorry I meant to `test/k4FWCoreTest/scripts`, that isn't installed, right?

**Comment by jmcarcell** [comment]
Yes, moved.

**Pull request merged**
